TRUSTED_DOMAINS = {
    "google.com", "accounts.google.com", "youtube.com", "gmail.com", "cloud.google.com",
    "openai.com", "chatgpt.com", "github.com", "gitlab.com", "stackoverflow.com",
    "microsoft.com", "windows.com", "office.com", "azure.com",
    "apple.com", "icloud.com",
    "amazon.com", "amazon.in", "aws.amazon.com",
    "oracle.com", "ibm.com",
    "facebook.com", "instagram.com", "whatsapp.com", "web.whatsapp.com",
    "messenger.com", "twitter.com", "x.com", "linkedin.com",
    "reddit.com", "discord.com", "telegram.org", "snapchat.com",
    "zoom.us", "skype.com",
    "paypal.com", "stripe.com", "visa.com", "mastercard.com", "americanexpress.com",
    "bankofamerica.com", "chase.com", "wellsfargo.com", "citibank.com", "hsbc.com",
    "icicibank.com", "hdfcbank.com", "sbi.co.in", "axisbank.com", "kotak.com",
    "paytm.com", "phonepe.com", "gpay.google.com",
    "flipkart.com", "myntra.com", "snapdeal.com", "ebay.com", "aliexpress.com",
    "etsy.com", "walmart.com", "target.com", "swiggy.com", "zomato.com",
    "uber.com", "ola.com",
    "wikipedia.org", "coursera.org", "udemy.com", "edx.org", "khanacademy.org",
    "nptel.ac.in", "mit.edu", "harvard.edu", "stanford.edu",
    "iitm.ac.in", "iitb.ac.in",
    "gov.in", "india.gov.in", "uidai.gov.in", "digilocker.gov.in",
    "irs.gov", "gov.uk", "usa.gov", "who.int", "un.org",
    "netflix.com", "primevideo.com", "hotstar.com", "hulu.com",
    "spotify.com", "soundcloud.com", "gaana.com", "jiosaavn.com",
    "imdb.com", "rottentomatoes.com", "medium.com", "quora.com",
    "bitbucket.org", "npmjs.com", "pypi.org", "docker.com", "kubernetes.io",
    "postman.com", "vercel.com", "netlify.com", "heroku.com",
    "digitalocean.com", "cloudflare.com", "linode.com",
    "outlook.com", "hotmail.com", "live.com", "proton.me", "protonmail.com",
    "zoho.com", "notion.so", "trello.com", "slack.com", "asana.com",
    "evernote.com", "dropbox.com", "box.com", "google.co.in", "maps.google.com",
    "booking.com", "airbnb.com", "makemytrip.com", "goibibo.com", "irctc.co.in",
    "cleartrip.com", "expedia.com", "tripadvisor.com",
    "bbc.com", "cnn.com", "nytimes.com", "theguardian.com", "reuters.com",
    "forbes.com", "bloomberg.com", "economist.com", "timesofindia.com",
    "hindustantimes.com", "ndtv.com", "indiatoday.in",
    "geeksforgeeks.org", "leetcode.com", "hackerrank.com", "codeforces.com",
    "topcoder.com", "freecodecamp.org", "w3schools.com", "tutorialspoint.com",
    "udacity.com", "pluralsight.com",
    "steamcommunity.com", "steampowered.com", "epicgames.com", "origin.com",
    "riotgames.com", "minecraft.net", "roblox.com", "playstation.com", "xbox.com",
    "cdc.gov", "mayoclinic.org", "webmd.com", "healthline.com", "nhs.uk",
    "nic.in", "incometax.gov.in", "gst.gov.in", "parivahan.gov.in",
    "passportindia.gov.in", "epfindia.gov.in", "esic.gov.in", "mygov.in",
    "data.gov.in", "mca.gov.in", "ajio.com", "meesho.com", "nykaa.com",
    "tatacliq.com", "reliancedigital.in", "shopclues.com",
    "jio.com", "airtel.in", "vodafoneidea.com", "bsnl.co.in", "actcorp.in", "excitel.com",
    "indianrail.gov.in", "redbus.in", "ixigo.com", "yatra.com", "rapido.bike",
    "sonyliv.com", "zee5.com", "voot.com", "thehindu.com", "news18.com",
    "firstpost.com", "moneycontrol.com",
    "nta.ac.in", "cbse.gov.in", "ugc.ac.in", "aicte-india.org", "swayam.gov.in",
    "byjus.com", "unacademy.com", "vedantu.com", "toppr.com",
    "tcs.com", "infosys.com", "wipro.com", "hcltech.com", "techmahindra.com",
    "relianceindustries.com", "adani.com", "tatagroup.com", "mahindra.com", "itcportal.com",
    "zerodha.com", "groww.in", "upstox.com", "angelone.in", "5paisa.com",
    "icicidirect.com", "hdfcsec.com", "kotaksecurities.com", "sharekhan.com",
    "motilaloswal.com", "axisdirect.in", "sbicapsec.com", "edelweiss.in",
    "nseindia.com", "bseindia.com", "sebi.gov.in", "nsdl.co.in", "cdslindia.com",
    "mcxindia.com", "amfiindia.com", "camsonline.com", "kfintech.com",
    "mfcentral.com", "kuvera.in", "paytmmoney.com", "coin.zerodha.com",
    "interactivebrokers.com", "etoro.com", "tradingview.com", "webull.com",
    "robinhood.com", "fidelity.com", "tdameritrade.com", "schwab.com",
    "wazirx.com", "coinbase.com", "binance.com", "coindcx.com", "coinswitch.co",
    "kraken.com", "bitstamp.net", "fxstreet.com", "oanda.com", "forex.com",
    "icmarkets.com", "pepperstone.com", "exness.com"
}